application/buyers/__init__.py
from flask import Blueprint

buyers = Blueprint('buyers', __name__)

from . import views

application/buyers/views.py
from . import buyers
from model import Model
from flask import render_template, jsonify, request

@buyers.route('/buyers', methods=['GET', 'POST'])
def index():
  if request.method == 'GET':
    buyers = []
    for buyer in Model.execute('SELECT first, last, id FROM buyers'):
      buyer = {
        "name": "{} {}".format(buyer[0], buyer[1]),
        "id": buyer[2]
      }
      buyers.append(buyer)
      print("INDEX BUYER:", buyer)
    return render_template('buyers/index.html', buyers=buyers)

  if request.method == 'POST':
    buyer = request.get_json()
    first, last = buyer["name"].split()
    Model.insert_in("buyers", first=first, last=last)
    #create buyer
    return jsonify(**buyer)

@buyers.route('/buyers/<int:buyer_id>', methods=['GET', 'PUT', 'DELETE'])
def show(buyer_id):
  #find buyer with buyer_id

  if request.method == 'GET':
    buyer = Model.execute('SELECT first, last, id FROM buyers WHERE id={}'.format(buyer_id)).fetchone()
    print("GET BUYER:", buyer)
    buyer = {
      "name": "{} {}".format(buyer[0], buyer[1]),
      "id": buyer[2]
    }

    orders = []
    for order in Model.execute('SELECT id, buyer, description, total FROM buyer_orders WHERE buyer={}'.format(buyer_id)):
      print("ORDER:", order)
      oid = order[0]
      order = {
        "id": order[0],
        "description": order[2],
        "total": order[3]
      }

      purchases = []
      for p in Model.execute('SELECT cookie, warehouse, buyer_order, amount FROM purchases WHERE buyer_order={}'.format(oid)):
        p = {
          "cookie": p[0],
          "warehouse": p[1],
          "amount": p[3]
        }
        purchases.append(p)

      order["purchases"] = purchases
      orders.append(order)
    buyer["orders"] = orders
    return jsonify(**buyer)

  if request.method == 'PUT':
    update = request.get_json()
    first, last = update["name"].split(" ")
    #update buyer with this information
    conn, cur = Model.make_cursor()
    cur.execute('''
    UPDATE buyers
    SET first="{}", last="{}"
    WHERE id={}
    '''.format(first, last, buyer_id))
    conn.commit()
    return "OK"

  if request.method == 'DELETE':
    #delete buyer with id = buyer_id
    conn, cur = Model.make_cursor()
    cur.execute('DELETE FROM buyers WHERE id={}'.format(buyer_id))
    conn.commit()
    return "OK"

@buyers.route('/signin', methods=['POST'])
def signin():
  conn, cur = Model.make_cursor()
  data = request.get_json()
  response = {}
  first = data["name"]
  password = data["password"]
  user = cur.execute('SELECT password FROM buyers WHERE first = "{}"'.format(first)).fetchone()
  response["ok"] = password == user[0]
  return jsonify(**response)

@buyers.route('/buyers/shop', methods=['GET', 'POST'])
def shop():
  conn, cur = Model.make_cursor()

  if request.method == 'GET':
    return render_template("buyers/shop.html")

  if request.method == 'POST':
    update = request.get_json()
    total = 0
    buyer = update['buyer']
    del update['buyer']
    print(buyer)
    print(update)

    buyer = cur.execute('SELECT id FROM buyers WHERE first = "{}"'.format(buyer)).fetchone()[0]
    for cookie, amt in update.items():
      price = float(cur.execute('SELECT price FROM cookies WHERE name = "{}"'.format(cookie)).fetchone()[0])
      total += price

    cur.execute('''
    INSERT INTO buyer_orders(buyer, total)
    VALUES ({}, {})
    '''.format(buyer, total))

    conn.commit()
    order = cur.lastrowid

    for cookie, amt in update.items():
      price = float(cur.execute('SELECT price FROM cookies WHERE name = "{}"'.format(cookie)).fetchone()[0])
      warehouse = cur.execute('SELECT warehouse FROM stock WHERE cookie = "{}"'.format(cookie)).fetchone()[0]
      print(warehouse, price)

      cur.execute('''
      INSERT INTO purchases(cookie, warehouse, buyer_order, amount)
      VALUES ("{}", "{}", {}, {})
      '''.format(cookie, warehouse, order, amt))

      cur.execute('''
      UPDATE stock
      SET quantity = quantity - {}
      WHERE cookie = "{}" and warehouse = "{}"
      '''.format(amt, cookie, warehouse))

    conn.commit()
    print(total)
    return "OK"

application/templates/buyers/index.html
{% extends "base.html" %}
{% block main %}
{{ super() }}
<div class="col-md-6">
  <h2>Buyers <button id="add" class="btn btn-default pull-right">Add new</button></h2>
  <ul id="buyers-list" class="list-group">
    {% for buyer in buyers %}
    <button id="buyer-{{ buyer.id }}" class="list-group-item">
      <h4>{{ buyer.name }}</h4>
    </button>
    {% endfor %}
  </ul>
</div>

<div id="side-content" class="col-md-6">
  <script id="create-template" type="x-tmpl-mustache">
  <form>
    <h2>Signup</h2>  
    <div class="form-group">
      <input name="name" type="text" class="form-control" placeholder="Name">
    </div>
    <button class="btn btn-default">Signup</button>
  </form>
  </script>

  <script id="view-template" type="x-tmpl-mustache">
  {%raw%}
  <h2>{{ name }}<button id="edit" class="btn btn-default pull-right">Edit</button></h2>
  <div class="well well-lg">
    <h3>Addresses</h3>
    {{#addresses}}
    <h4><small>{{ address }}</small></h4>
    {{/addresses}}
    <h3>Orders</h3>
    <ul class="list-group">
    {{#orders}}
      <li class="list-group-item">
        <h5>Order #{{id}}</h5>
        <h5>Total: ${{total}}</h5>
        <ul class="list-group">
          {{#purchases}}
          <li class="list-group-item"><span class="badge">{{ amount }}</span> Cookie: {{cookie}}<br> Warehouse: {{warehouse}}</li>
          {{/purchases}}
        </ul>
      </li>
    {{/orders}}
    </ul>
    <button id="delete" class="btn btn-danger">Delete</button>
  </div>
  {%endraw%}
  </script>

  <script id="edit-template" type="x-tmpl-mustache">
  {%raw%}
  <form>
    <h2>Edit</h2>  
    <div class="form-group">
      <input name="name" type="text" class="form-control" placeholder="{{ name }}">
    </div>
    <button class="btn btn-default">Submit</button>
  </form>
  {%endraw%}
  </script>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
  var createTemplate
  var viewTemplate
  var editTemplate 
  var $content
  var current = {}

  $(function(){
    createTemplate = $('#create-template').html()
    viewTemplate = $('#view-template').html()
    editTemplate = $('#edit-template').html()
    $content = $('#side-content')

    loadCreatePage()
    $("button#add").click(loadCreatePage)

    $('#buyers-list button').click(function(){
      var buyer_id = this.id.match(/\d+/)[0]
      $.get('buyers/' + buyer_id)
        .then(function(data){
          current.name = data.name
          current.id = data.id

          var content = Mustache.render(viewTemplate, data)
          $content.html(content)
          $content.find('button#edit').click(loadEditPage)
          $content.find('button#delete').click(function(){
            $.ajax('buyers/' + buyer_id, {
              method: 'DELETE'
            })
              .then(function(data){console.log(data)})
          })
        })
    })
  })

  function loadEditPage() {
    var content = Mustache.render(editTemplate, current)
    $content.html(content)
    $content.find('form').submit(function(e){
      e.preventDefault()
      var values = {}
      $.each($content.find('form').serializeArray(), function(i, field){
        if(field.value) {
          values[field.name] = field.value
        }
      })

      $.ajax('buyers/' + current.id, {
        contentType: 'application/json',
        dataType: 'json',
        data: JSON.stringify(values),
        method: 'PUT'
      })
        .done(function(data){
          console.log(data)
        })
    })
  }

  function loadCreatePage() {
    $content.html(createTemplate)
    $content.find('form').submit(function(e){
      e.preventDefault()
      var values = {}
      $.each($content.find('form').serializeArray(), function(i, field){
        if(field.value) {
          values[field.name] = field.value
        }
      })

      $.ajax('buyers', {
        contentType: 'application/json',
        dataType: 'json',
        data: JSON.stringify(values),
        method: 'POST'
      })
        .done(function(data){
          console.log(data)
        })
    })
  }
</script>
{% endblock%}

application/templates/buyers/shop.html
{% extends "base.html" %}
{% block main %}
{{ super() }}
<div class="col-md-6">
  <h2>Buy Stuff</h2>
  <form id="target">
    <script id="template" type="x-tmpl-mustache">
    {% raw %}
    {{#cookies}}
      {{ name }}: <input style="width:75px;" name="{{ name }}" type="number" class="form-control">
    {{/cookies}} 
    {%endraw%}
    </script>    
     
  </form>
  <br>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
  template = $('#template').html()
  target = $('#target')
  var data = {"cookies": []}
  var cookies = JSON.parse(localStorage.getItem('cookies'))
  cookies.forEach(function(cookie){
    data.cookies.push({
      "name": cookie
    })
  })

  var content = Mustache.render(template, data)
  target.html(content)
  target.append('<br><button id="buy" class="btn btn-primary">Purchase</button>')
  $('#target').submit(function(e){
    e.preventDefault()
    var values = {}
    $.each($('#target').serializeArray(), function(i, field){
      if(field.value) {
        values[field.name] = field.value
      }
    })

    values['buyer'] = localStorage.getItem('user')

    $.ajax({
      url: '{{ url_for("buyers.shop", _external=True) }}',
      contentType: 'application/json',
      dataType: 'json',
      data: JSON.stringify(values),
      method: 'POST'
    })
      .always(function(data){
        console.log("Clearing")
        localStorage.removeItem('cookies')
      })
    console.log(values)
  })
</script>
{% endblock %}

application/templates/buyers/show.html
{% extends "base.html" %}
{% block body %}
{{ super() }}
<div class="column">
  <h2>{{ buyer.name }}</h2>
  <h3>{{ buyer.address }}</h3>

  <ul class="orders">
  {% for order in buyer.orders %}
    <li>
      #{{ order.id }}: 
      <ul>
        {% for cookie in order.cookies %}
        <li>
          {{ cookie.name }}: {{ cookie.price }}
        </li>
        {% endfor %}
      </ul>
      {{ order.total }}
    </li>
  {% endfor %}
  </ul>

</div>
{% endblock %}